sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=3.2.4
sonar.sources=.
sonar.exclusions=venv/**,__pycache__/**,test_*.py,k8s/**,*.yaml,*.yml
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
